name: 🚀 Publish Python Package

on:
  workflow_run:
    workflows: ["🧪 Run Tests"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    name: Build and Publish to PyPI
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check PyPI version
        run: |
          VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          echo "Current version: $VERSION"
          if python -c "import requests; r=requests.get('https://pypi.org/pypi/omada-client/json').json(); assert '$VERSION' not in r['releases']"; then
              echo "Version available, continue publishing."
          else
              echo "Version $VERSION already exists on PyPI. Skipping publish."
              exit 78  # exit with 78 skips job in GitHub Actions
          fi

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*